### ISSUE TITLE
Remove attribution button

### ISSUE THREAD

**Issue by desmeit** [m0nac0/flutter-mapbox-gl#174]
Is it possible to remove or edit (Color etc.) the attribution button? 

https://docs.mapbox.com/ios/maps/guides/#attribution

Thanks and best regards

**Comment by BartoszStasiurka** [comment]
Try something like this:
```
MaplibreMap(
  ...
  attributionButtonPosition: AttributionButtonPosition.BottomLeft,
  attributionButtonMargins: Point(-100, -100),
)
```

**Comment by mariusvn** [comment]
I still put a disclaimer here, some map publishers **require** an attribution. For example, OpenStreetMap require an attribution like `© OpenStreetMap contributors`.

Here is a bit of why it's important (got from their page [here](https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines)) :

> ### Why attribution is important
> 
> Attribution encourages others to use OSM data by making obvious where it is coming from and under which conditions it can be used.
> 
> It also helps recruit contributors and encourages them to contribute more, boosting a virtuous circle that maximises the quality of the map for everyone.
> 
> Finally, it is not only a legal obligation under the ODbL but also a moral duty of data reusers to give credit where credit is due. 

So when you disable the attribution button, **always** check your rights to do it.

now @m0nac0, can you close this issue ? thanks ;)

**Comment by m0nac0** [comment]
Thanks for the additional explanation @mariusvn 👍

**Comment by LibraryLibrarian** [comment]
Hi,

I recently started using this library to display maps in my Flutter app. When I checked the map, I noticed there's an info button (attribution button) in the bottom-left corner that displays information about the map provider and library when tapped.

Since I want to include attribution information for the libraries and map data I'm using in my app's About screen, I tried to remove the info button from the map. However, I couldn't find a proper way to do so, and that's when I found this issue.

I don't think the suggested workaround of using negative coordinates to push the button off-screen is a good solution. It's more of a hack than a proper implementation, and from a UI development perspective, it's not an ideal approach.

Instead, I believe we should add a new flag that allows developers to explicitly disable the attribution button by setting it to `false`.

I understand that attribution is important and must be displayed. However, I personally think it's not ideal that the library limits how developers can provide attribution. Developers should have the flexibility to implement attribution in their own way—for example, in an About screen or a dedicated attribution section.

Additionally, the attribution dialog UI on Android looks quite outdated. It appears to be from an early version of Android, which doesn't fit well with the modern Material Design language used in current Android versions. This is another reason why I believe giving users the option to hide the built-in attribution (so they can implement their own) would be beneficial.

If this aligns with the project's direction, I'm happy to create a PR that adds the functionality to hide the attribution button.

Thanks!
