### ISSUE TITLE
Better maintainer presence

### ISSUE THREAD

**Issue by mariusvn** [m0nac0/flutter-mapbox-gl#195]
Hello,

Its been three months since the maintainer of this repo is not active and the library needs updates because it still has some breaking bugs like the `getVisibleRegion` method not working properly or the back screen on new android versions (those are fixed in PRs).

There is also breaking bugs like an app crash when disposing the map sometimes.

With all my respect to m0nac0, I suggest to add some maintainers or move to a fork to allow the community to merge the PRs and create public release on pub.dev .

I can understand the maintainer absence because we all have a life but i just suggest to have a better activity here.

have a great day everyone,

Marius

**Comment by m0nac0** [comment]
Indeed I haven't been able to be as active here as I'd like to...
I'm open to adding additional maintainers here, if someone is interested in that, or possibly letting the maplibre org transfer the repo to their organization, if they are interested in that.
But it is quite difficult to develop this plugin and review contributions since usually those should work on all 3 platforms. Especially testing on iOS is difficult for me.

Regarding the map crashing sometimes when disposing, this bug has been discussed quite extensively in https://github.com/flutter-mapbox-gl/maps, where this repo was forked from. There are some fixes upstream, but so far they are explicitly labeled as not production ready. The core issue seem to have been changes made by the flutter team, which break the (quite complicated) way these plugings integrate the underlying native libraries through platform views. If the patches in flutter-mapbox-gl seem to fix the issue (together with recent flutter versions) we can probably port them over to this repo.

**Comment by mariusvn** [comment]
I understand, I may be intersted to join you if i continue to work with maplibre in the future. I prefer to have experience with the project before candidating to the maintainer's right. 
btw, I also have your IOS issue, only android here.

About the crash, i take notes about that and if any news is happening, lets talk about it in the respecting issue.

I understand your position. I made this post because I use flutter maplibre gl at work so the delay is sometimes frustrating but anyway i have a fork where i update the main branch with the needed pull requests are popping.

**Comment by JulianBissekkou** [comment]
Can I still apply as a maintainer of this package? 👀
