### ISSUE TITLE
Adding additional attribution

### ISSUE THREAD

**Issue by kuhnroyal** [m0nac0/flutter-mapbox-gl#210]
Is there any way to add additional attribution items?
I don't have OSM attribution which is required.

**Comment by kuhnroyal** [comment]
Additionally on Android I have the info icon but can not press it.

**Comment by mariusvn** [comment]
> Is there any way to add additional attribution items?
> I don't have OSM attribution which is required.

When you add a source, in the source properties, you should have the `attribution` key.

We might have a regression because the attribution is not listed in the attribution list on my side, which is not the expected behaviour. Can you tell me if its working on your side ?

> Additionally on Android I have the info icon but can not press it.

Works on my side, you may have a `PointerInterceptor` over it or something like that.

**Comment by kuhnroyal** [comment]
Hmm I haven't used the source properties before. That might have worked but since we are in Flutter, I just added a dialog/action-sheet and hid the original info icon.
